### ISSUE TITLE
Alias Deft.promise.* -> Ext.promise.*

### ISSUE THREAD

**Issue by superstructor** [deftjs/DeftJS5#12]
DeftJS promises are now included as the `Ext.promise.*` namespace in Ext JS 6+. We should simply alias and deprecate the DeftJS namespace for backwards compatibility and stop shipping this redundant code.

**Comment by joeguaneri** [comment]
@superstructor Working on it but having a problem dealing with the statics. I'm having trouble getting those to defer to the Ext version. The class methods work great with the extends but there isn't a mechanism to necessarily deal with the statics.

**Comment by brian428** [comment]
Could the Deft statics just delegate to the Sencha class(es)?

**Comment by joeguaneri** [comment]
I've tried straight delegation and the tests fail.  I'm a little puzzled as to why.

**Comment by joeguaneri** [comment]
I've created a branch in my fork with what I was currently thinking of.
https://github.com/jguaneri/DeftJS5/tree/promises

This fails badly :(

**Comment by brian428** [comment]
hmm Travis says it is still passing for your branch. What's failing?

**Comment by joeguaneri** [comment]
I see a failure:
https://travis-ci.org/jguaneri/DeftJS5/builds/80477812

**Comment by brian428** [comment]
Sorry, the badge showed it as passing! The first thing that comes to mind is that the class isn't being included in the build output for some reason? Maybe try adding back in the requires entry for Deft.promise.Deferred? (https://github.com/deftjs/DeftJS5/blob/371378f14bbf55226d065805c24d390aa80e3ebb/packages/deft/src/coffee/promise/Promise.coffee#L74)

**Comment by joeguaneri** [comment]
I added back the requires entry.  Still failed.  https://travis-ci.org/jguaneri/DeftJS5/builds/81409916.  I'm going to dig around more in this.
