### ISSUE TITLE
Confirm new Sencha VC event handling still works

### ISSUE THREAD

**Issue by brian428** [deftjs/DeftJS5#3]
Ensure that the built-in Sencha VC event handling still works correctly when using the Deft JS VC.

**Comment by benquarmby** [comment]
This works for me in the alpha. Event listener blocks throughout the view hierarchy are tied to the Deft 5 VC.

If the listeners are at the top level (directly on the view class prototype) then an explicit 'controller' scope is required. Otherwise it expects to find handlers on the view:

``` javascript
listeners: {
    beforerender: 'onViewBeforeRender',
    scope: 'controller'
}
```

**Comment by brian428** [comment]
Right, all of the view event handling is now done by the underlying Sencha ViewController class.
